### ISSUE TITLE
xsd schema to C# classes

### ISSUE THREAD

**Issue by shimontropper** [open-psa/schemas#1]
Hi,
I'm trying to convert mef.xsd file to c# classes by using microsoft tool: xsd.exe, but I receive the following error: 

> Schema validation warning: Multiple definition of element 'periodic-test' causes the content model to become ambiguous. A content model must be formed such that during validation of an element information item sequence, the particle contained directly, indirectly or implicitly therein with which to attempt to validate each item in the sequence in turn can be uniquely determined without examining the content or attributes of that item, and without any information about the items in the remainder of the sequence. Line 1097, position 8.
> 
> Schema validation warning: Elements with the same name and in the same scope must have the same type. Line 1108, position 8.

Is there a way to create c# classes from mef schema?
Thanks,
Shimon

**Comment by rakhimov** [comment]
Hi @shimontropper ,
This erroneous overloading has been fixed in 7be72d5.
I believe you are somehow using the old schema
because even the line numbers in your error message does not refer to 'periodic-test'
in the schema in this repository.

As for the question on xsd -> c#.
Google is your friend:
https://stackoverflow.com/questions/27924162/transform-xsd-1-1-schema-to-c-sharp-class#29631156
https://stackoverflow.com/questions/5217665/how-to-generate-net-4-0-classes-from-xsd

**Comment by shimontropper** [comment]
Hi Olzhas Rakhimov,
You were right, mistakenly I did use the old schema, unfortunetly in 7be72d5
<https://github.com/open-psa/schemas/commit/7be72d5904e6d46743f5dfa0045a2e8ae3d8366a>
I
receive the following error when I generate C# classes:
Error: Error generating classes for schema 'mef'.
  - Group 'operation' from targetNamespace='' has invalid definition:
Circular group reference.

I used this command:
xsd.exe mef.xsd /classes

Regards,
Shimon Tropper

**Comment by rakhimov** [comment]
Hi @shimontropper ,
I'm wondering why you don't use the latest one from this repository.
Why are you checking out the older commits?

In the case of the xsd.exe,
there's nothing wrong with the MEF schema;
the limitation is of one xsd.exe not being able to deal with recursive constructs:
https://stackoverflow.com/questions/2388844/xsd-exe-and-circular-group-references
